receivers:
    opencensus:
        endpoint: 0.0.0.0:55678
  # zipkin:
  #   endpoint: 0.0.0.0:9411

exporters:
    logging:
        loglevel: info
        sampling_initial: 5
        sampling_thereafter: 200
    file:
        path: ./metrics.json

  # zipkin:
  #   url: "http://zipkin:9411/api/v2/spans"
  #   format: proto

  # jaeger_thrift:
  #   url: "http://jaeger:14268/api/traces"

processors:
    metrics_transform:
        metric_name: opdemo/process_counts
        action: update
        new_name: new/process_counts
        operations:
            - action: update_label
              label: client
              new_label: new/client
              value_actions:
                - value: cli
                  new_value: new/cli
                - value: repl
                  new_value: new/repl
  

# extensions:
#   health_check:
#   pprof:
#     endpoint: :1888
#   zpages:
#     endpoint: :55679

service:
  # extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
        receivers: [opencensus]
        exporters: [logging]
        processors: []
    metrics:
        receivers: [opencensus]
        exporters: [file]
        processors: [metrics_transform]
