receivers:
    opencensus:
        endpoint: 0.0.0.0:55678
  # zipkin:
  #   endpoint: 0.0.0.0:9411

exporters:
    logging:
        loglevel: info
        sampling_initial: 5
        sampling_thereafter: 200
    file:
        path: ./metrics.json

  # zipkin:
  #   url: "http://zipkin:9411/api/v2/spans"
  #   format: proto

  # jaeger_thrift:
  #   url: "http://jaeger:14268/api/traces"

processors:
    metricstransform:
        transforms:
            - metric_name: opdemo/process_counts
              action: update
              new_name: new/process_counts
              operations:
                - action: update_label
                  label: client
                  value_actions:
                    - value: cli
                      new_value: new/cli
                - action: aggregate_labels
                  label_set: [client]
                  aggregation_type: sum
            - metric_name: opdemo/line_lengths
              action: insert
              new_name: new/line_lengths
              operations:
                - action: update_label
                  label: client
                  new_label: new/client
  

# extensions:
#   health_check:
#   pprof:
#     endpoint: :1888
#   zpages:
#     endpoint: :55679

service:
  # extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
        receivers: [opencensus]
        exporters: [logging]
        processors: []
    metrics:
        receivers: [opencensus]
        exporters: [file]
        processors: [metricstransform]
